feat(codemod): elasticsearch migrations v8
codemod-com/codemod pull request #1259
Opened 2024-08-20 05:02 UTC by 35C4n0r

#### 📚 Description

#### 🔗 Linked Issue

#### 🧪 Test Plan

#### 📄 Documentation to Update

2024-08-20 21:13 UTC, mohebifar requested changes
Please make sure to add 

```json
"private": true
```

to packages that are not published to npm

2024-08-20 21:13 UTC, mohebifar commented on packages/codemods/elasticsearch/8/migrate-plugins-extend/package.json
> +  "devDependencies": {
```json
"private": true
```

2024-08-20 21:13 UTC, mohebifar commented on packages/codemods/elasticsearch/8/migration-recipe/package.json
> +  "type": "module"
```json
"private": true
```

2024-08-20 21:13 UTC, mohebifar commented on packages/codemods/elasticsearch/8/move-client-configurations/package.json
> +  "dependencies": {},
```json
"private": true
```

2024-08-20 21:13 UTC, mohebifar commented on packages/codemods/elasticsearch/8/rename-query-string/package.json
> +  "dependencies": {},
```json
"private": true
```

2024-08-20 21:13 UTC, mohebifar commented on packages/codemods/elasticsearch/8/unify-return-value/package.json
> +  "dependencies": {},
```json
"private": true
```

2024-08-21 04:06 UTC, 35C4n0r commented
@mohebifar thanks for the review :)
Made the changes.

2024-12-26 14:26 UTC, mohab-sameh commented
@35C4n0r Do you mind moving this to [`codemod-com/commons`](https://github.com/codemod-com/commons) as we're moving codemod package sources there? For now, I will close this PR.

2024-12-26 14:26 UTC, closed without merging